server:
  port: 9191

spring:
  security:
    user:
      name: jane-doe
      password: jane-doe123
      roles: USER

security:
  oauth2:
    client:
      client-id: app-mobile
      client-secret: app-mobile123
      access-token-validity-seconds: 3600
      authorized-grant-types: authorization_code,password,refresh_token,client_credentials
      scope: READ,WRITE
    authorization:
      check-token-access: permitAll